# Generated by Django 5.2.7 on 2025-12-31 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('visit_regn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(help_text='Unique File Number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('interim_status', models.CharField(choices=[('Processing', 'Processing'), ('Site Visit Required', 'Site Visit Required'), ('Addl Documents Awaited', 'Addl Documents Awaited'), ('Payment Pending', 'Payment Pending'), ('Closed', 'Closed')], default='Processing', max_length=50)),
                ('fee_receipt_no', models.CharField(blank=True, max_length=50, null=True)),
                ('fee_receipt_date', models.DateField(blank=True, null=True)),
                ('reply_to', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_date', models.DateField(blank=True, null=True)),
                ('remarks1', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks2', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks3', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_files', to='accounts.desk')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_file', to='visit_regn.visit')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('papers_submitted', models.TextField(help_text='Details of papers/documents submitted')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('office_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_submissions', to='filing.officefile')),
            ],
        ),
    ]
