# Generated by Django 5.2.7 on 2025-12-31 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('filing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officefile',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_files', to='accounts.office'),
        ),
        migrations.AddField(
            model_name='officefile',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officefile',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officefile',
            name='file_number',
            field=models.CharField(blank=True, help_text='Auto-generated File Number (Serial/Year)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='officefile',
            unique_together={('office', 'year', 'serial_number')},
        ),
    ]
