# Generated by Django 5.2.7 on 2026-01-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0002_officefile_office_officefile_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officefile',
            name='despatch_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Despatch ID / Memo No'),
        ),
        migrations.AddField(
            model_name='officefile',
            name='despatch_mode',
            field=models.CharField(blank=True, choices=[('By Hand', 'By Hand'), ('By Post', 'By Post'), ('eOffice', 'eOffice'), ('eDistrict', 'eDistrict'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officefile',
            name='reply_type',
            field=models.CharField(blank=True, choices=[('Certificate', 'Certificate'), ('Report', 'Report'), ('Statement of Facts', 'Statement of Facts'), ('Mozhi', 'Mozhi'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='officefile',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Pending'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
