# Generated by Django 5.2.7 on 2026-01-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0003_officefile_despatch_id_officefile_despatch_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officefile',
            name='interim_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Site Visit Required', 'Site Visit Required'), ('Addl Documents Awaited', 'Addl Documents Awaited'), ('Payment Pending', 'Payment Pending'), ('Sent for external verification report', 'Sent for external verification report'), ('Closed', 'Closed')], default='Processing', max_length=50),
        ),
    ]
