# Generated by Django 5.2.7 on 2026-01-06 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='e.g. 05', max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='is_headquarters',
            field=models.BooleanField(default=False, help_text='Is this the Taluk Headquarters?'),
        ),
        migrations.AlterField(
            model_name='office',
            name='code',
            field=models.CharField(help_text='e.g. 050317', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(help_text='Village Name, e.g. Nattakam', max_length=100),
        ),
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='e.g. 0503', max_length=20, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taluks', to='accounts.district')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='taluk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices', to='accounts.taluk'),
        ),
    ]
