# Generated by Django 5.2.7 on 2025-12-10 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_mode', models.CharField(choices=[('QR', 'QR Code'), ('KIOSK', 'Kiosk'), ('QUICK', 'Quick')], max_length=10)),
                ('token_issue_time', models.DateTimeField(auto_now_add=True)),
                ('token_attend_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ROUTED', 'Routed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('current_desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_visits', to='accounts.desk')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounts.office')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visit_regn.purpose')),
            ],
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('ROUTED', 'Routed'), ('ASSIGNED', 'Assigned'), ('ATTENDED', 'Attended'), ('TRANSFERRED', 'Transferred'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('COMMENT', 'Comment')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffmember')),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='accounts.desk')),
                ('to_desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='accounts.desk')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='visit_regn.visit')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTokenCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.office')),
            ],
            options={
                'unique_together': {('office', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['office', 'token'], name='visit_regn__office__9970f9_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['office', 'token_issue_time'], name='visit_regn__office__c8d59c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('office', 'token')},
        ),
    ]
