# Generated by Django 5.2.7 on 2025-12-31 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filing', '0002_officefile_office_officefile_serial_number_and_more'),
        ('visit_regn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='related_office_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_visits', to='filing.officefile'),
        ),
    ]
