# Generated by Django 5.2.7 on 2025-12-22 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visit_regn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_number', models.CharField(blank=True, help_text='Thandaper Number / Landholder ID', max_length=50, null=True)),
                ('remarks1', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks2', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks3', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed'), ('OPEN_FILE', 'Open File')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='visit_regn.visit')),
            ],
        ),
    ]
