# Generated by Django 5.2.7 on 2026-01-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='block',
            field=models.CharField(blank=True, help_text='Block Identifier (e.g. Block 1, Block 2)', max_length=50, null=True),
        ),
    ]
