# Generated by Django 5.2.7 on 2026-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='block',
            field=models.CharField(blank=True, help_text='Block Identifier (e.g. Blk1)', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tp_number',
            field=models.CharField(blank=True, help_text='Thandaper Number / Landholder ID', max_length=5, null=True),
        ),
    ]
