# Generated by Django 5.2.7 on 2025-12-14 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('visit_regn', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='accounts.desk')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desk_queue', to='visit_regn.visit')),
            ],
            options={
                'verbose_name': 'Desk Queue Item',
                'verbose_name_plural': 'Desk Queue Items',
                'ordering': ['assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.desk')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='accounts.office')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='visit_regn.purpose')),
            ],
            options={
                'verbose_name': 'Routing Rule',
                'verbose_name_plural': 'Routing Rules',
                'unique_together': {('office', 'purpose')},
            },
        ),
    ]
