# Generated by Django 5.2.7 on 2025-12-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tapal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=250)),
                ('tapal_type', models.CharField(choices=[('GOVT', 'Government Order'), ('PUBLIC', 'Public Petition'), ('COURT', 'Court Case'), ('INTERNAL', 'Internal Memo')], default='PUBLIC', max_length=20)),
                ('received_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TapalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
