# Generated by Django 5.2.7 on 2025-12-07 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tapal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tapalmovement',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tapals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tapalmovement',
            name='tapal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='tapal.tapal'),
        ),
        migrations.AddField(
            model_name='tapalmovement',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_tapals', to=settings.AUTH_USER_MODEL),
        ),
    ]
